            - name: Upload a Build Artifact
  uses: actions/upload-artifact@v5.0.0
  with:
    # Artifact name
    name: # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: 
    # The desired behavior if no files are found using the provided path.
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: # optional, default is warn
    # Duration after which artifact will expire in days. 0 means using default retention.
Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: # optional
    # The level of compression for Zlib to be applied to the artifact archive. The value can range from 0 to 9: - 0: No compression - 1: Best speed - 6: Default compression (same as GNU Gzip) - 9: Best compression Higher levels will result in better compression, but will take longer to complete. For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.

    compression-level: # optional, default is 6
    # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.

    overwrite: # optional, default is false
    # If true, hidden files will be included in the artifact. If false, hidden files will be excluded from the artifact.

    include-hidden-files: # optional, default is false
          name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned, labeled]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    # Trigger on @claude mentions or issue assignments
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Assistant
        uses: grll/claude-code-action@beta
        with:
          # === Authentication Options ===
          # Option 1: Direct Anthropic API (uncomment to use)
          # anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # Option 2: OAuth for Claude Max subscribers (recommended - uncomment to use)
          use_oauth: true
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          secrets_admin_pat: ${{ secrets.SECRETS_ADMIN_PAT }}

          # === Configuration ===
          timeout_minutes: "60"
          max_turns: "10"
          use_sticky_comment: false
          trigger_phrase: "@claude"

          # === Tool Access ===
          # Allow Claude to run tests and build commands
          allowed_tools: |
            Bash(npm install)
            Bash(npm run build)
            Bash(npm run test)
            Bash(npm run lint)
            Bash(npm run type-check)
            Bash(npm run format)
            Bash(git diff)
            Bash(git log)
            Edit
            Read
            Write
            Glob
            Grep

          # === Custom Instructions ===
          custom_instructions: |
            You are an expert full-stack developer assisting with the Beehive platform.

            ## Platform Overview
            - **Type**: AI-powered autonomous publishing platform
            - **Stack**: Next.js, TypeScript, Tailwind, Supabase, CrewAI
            - **Purpose**: Multi-agent orchestration with BeeHive Codex rituals

            ## Key Responsibilities
            1. **Code Review**: Analyze PRs for quality, security, and performance
            2. **Feature Implementation**: Help implement new features following the architecture
            3. **Bug Fixes**: Debug issues and provide solutions
            4. **Documentation**: Keep docs in sync with code changes
            5. **Testing**: Suggest and implement test cases
            6. **Best Practices**: Enforce TypeScript strict mode, proper error handling

            ## Architecture Patterns
            - Use platform integrations: `lib/platforms/` (Instagram, TikTok, YouTube)
            - Follow BeeHive rituals: Badge, Metrics, Echo, History
            - Leverage CrewAI for agent orchestration
            - Use MCP servers for tool integration
            - Maintain type safety with TypeScript strict mode

            ## Quality Standards
            - All code must pass: lint, type-check, unit tests, E2E tests
            - PRs require meaningful commit messages
            - Documentation updates for new features
            - No hardcoded secrets or API keys
            - Use environment variables for config

            ## When Asked
            - Code reviews: Focus on quality, security, performance
            - Fixes: Provide complete solutions with tests
            - Features: Ask clarifying questions first
            - Documentation: Keep all docs updated together

          # === Branches ===
          base_branch: "main"
          branch_prefix: "claude/"

          # === Environment Variables ===
          claude_env: |
            NODE_ENV: development
            DEBUG: false

      - name: Comment on completion
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            console.log('✅ Claude Code Assistant completed');
