name: PR AutoMerge via Codex
on:
  pull_request:
    types: [labeled]
jobs:
  auto-merge:
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: read
      statuses: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        run: npm install
      - name: Run PR AutoMerge
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: node scripts/pr-automerge.js ${{ github.repository_owner }} ${{ github.event.pull_request.base.repo.name }} ${{ github.event.pull_request.number }}

